import type { Metadata } from "next";
import {
  Inter,
  Outfit,
  Nanum_Gothic,
  Nanum_Brush_Script,
  Nanum_Pen_Script,
} from "next/font/google";
import "./globals.css";
import { ClerkProvider, currentUser } from "@clerk/nextjs";
import NavBar from "@/components/NavBar";
import { redirect } from "next/navigation";

const outfit = Nanum_Pen_Script({ subsets: ["latin"], weight: "400" });

export const metadata: Metadata = {
  title: "Hey Taxi",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // const user = await currentUser();
  // if (!user) {
  //   redirect("/sign-in");
  // }
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={outfit.className}>
          <NavBar />
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
